# site setting

title: Deep0Thinking's Blog

remote_theme: jekyll/minima

show_description: true

header_pages:
  - all-tags.md
  - archive.md
  - about.md

google_analytics: G-880676458P

plugins:
  - jekyll-toc